baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Hugo Title'
theme = 'delphinus'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "My description"
  footerSubtitle = "My footer subtitle"
  organization = "Aarhus University"
